# Generated by Django 4.0.4 on 2022-05-12 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Harmonogram',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('czas_start', models.DateTimeField(blank=True, null=True)),
                ('czas_koniec', models.DateTimeField(blank=True, null=True)),
                ('typ', models.CharField(blank=True, max_length=1, null=True)),
            ],
            options={
                'db_table': 'harmonogram',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Prowadzacy',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('imie', models.CharField(blank=True, max_length=30, null=True)),
                ('nazwisko', models.CharField(blank=True, max_length=30, null=True)),
                ('rola', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'prowadzacy',
                'managed': False,
            },
        ),
    ]
